# Configuracion del pipeline. Valores tomados de tu runBITACORA.sh real (Mtub H37Rv).

# ---- BITACORA ----
bitacora_scriptdir: "/users-d2/j.rondon/arsR/SSNs_results_PAPER/bitacora_results/bitacora_SSN_Jun26/Scripts"
query_db: "/users-d2/j.rondon/arsR/SSNs_results_PAPER/bitacora_results/bitacora_SSN_Jun26/databases"
bitacora_gemomap: ""

bitacora_threads: 10
bitacora_gemoma: "F"
bitacora_maxintron: 0
bitacora_genomicblastp: "F"
bitacora_addfilter: "T"
bitacora_filterlength: 60
bitacora_retainnonfilter: "F"
bitacora_clean: "T"

bitacora_keep_suffix: "_genomic_and_annotated_proteins_trimmed_idseqsclustered"

# ---- MetalNet2 ----
metalnet_python: "/users-d2/j.rondon/miniconda3/envs/metalnet/bin/python"
metalnet_script: "/users-d2/j.rondon/programas/MetalNet2/model/scripts/run_prediction_workflow.py"
metalnet_msa_source: "colabfold"
metalnet_use_gpu: false
metalnet_threads: 4
